theme_d_w = {
    "light": {
        "accent": "#2186f4",
        "accent_positive": "#017500",
        "accent_negative": "#C20000",
        "background_content": "#F9f9f9",
        "background_page": "#ffffff",
        "body_text": "#3f3f3f",
        "border": "rgb(229,229,229)",
        "border_style": {
            "name": "underlined",
            "borderWidth": "0px 0px 1px 0px",
            "borderStyle": "solid",
            "borderRadius": 0,
        },
        "button_border": {"width": "1px", "color": "#1f78b4", "radius": "10px"},
        "button_capitalization": "uppercase",
        "button_text": "#1f78b4",
        "button_background_color": "white",
        "control_border": {
            "width": "0px 0px 1px 0px",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "control_background_color": "white",
        "control_text": "#606060",
        "card_margin": "15px",
        "card_padding": "5px",
        "card_border": {
            "width": "0px 0px 0px 0px",
            "style": "solid",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "card_background_color": "white",
        "card_box_shadow": "0 0 0 rgba(0,0,0,0.12), 0 0 0 rgba(0,0,0,0.24)",
        "card_outline": {"width": "1px", "style": "solid", "color": "#e2e2e2"},
        "card_header_margin": "0px",
        "card_header_padding": "10px",
        "card_header_border": {
            "width": "0px 0px 1px 0px",
            "style": "solid",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "card_header_background_color": "white",
        "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
        "breakpoint_font": "1200px",
        "breakpoint_stack_blocks": "700px",
        "colorway": [
            "#119dff",
            "#66c2a5",
            "#fc8d62",
            "#e78ac3",
            "#a6d854",
            "#ffd92f",
            "#e5c494",
            "#b3b3b3",
        ],
        "colorscale": [
            "#1f78b4",
            "#4786bc",
            "#6394c5",
            "#7ba3cd",
            "#92b1d5",
            "#a9c0de",
            "#bed0e6",
            "#d4dfee",
            "#eaeff7",
            "#ffffff",
        ],
        "dbc_primary": "#7a4aff",
        "dbc_secondary": "#b9a6ff",
        "dbc_info": "#7fe4ff",
        "dbc_gray": "#adb5bd",
        "dbc_success": "#35dbb3",
        "dbc_warning": "#ffcc3e",
        "dbc_danger": "#ff2c6d",
        "font_family": "Open Sans, sans-serif",
        "font_family_header": "Open Sans, sans-serif",
        "font_family_headings": "Open Sans, sans-serif",
        "font_size": "14px",
        "font_size_smaller_screen": "13px",
        "font_size_header": "24px",
        "title_capitalization": "uppercase",
        "header_content_alignment": "spread",
        "header_margin": "0px 0px 15px 0px",
        "header_padding": "0px",
        "header_border": {
            "width": "0px 0px 1px",
            "style": "solid",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "header_background_color": "white",
        "header_box_shadow": "0 0 0 rgba(0,0,0,0.12), 0 0 0 rgba(0,0,0,0.24)",
        "header_text": "#606060",
        "heading_text": "#1e1e1e",
        "text": "#606060",
        "report_background_content": "#FAFBFC",
        "report_background_page": "white",
        "report_text": "black",
        "report_font_family": "Computer Modern",
        "report_font_size": "12px",
        "svg-icons-theme": "invert(0)",
        "dash_cloud_button_background_color": "#60bab6",
        "dbc_dark": "#111111",
        "dbc_light": "#f4f4f4",
        "header_right_border_color": "1px solid var(--text)",
        "kubernetes_banner_font_color": "white",
    },
    "dark": {
        "accent": "#2186f4",
        "accent_positive": "#017500",
        "accent_negative": "#C20000",
        "background_content": "#161A1D",
        "background_page": "#0e1012",
        "body_text": "#A0AABA",
        "border": "rgb(63,63,63)",
        "svg-icons-theme": "invert(1)",
        "border_style": {
            "name": "underlined",
            "borderWidth": "0px 0px 1px 0px",
            "borderStyle": "solid",
            "borderRadius": 0,
        },
        "button_border": {"width": "1px", "color": "#2186f4", "radius": "10px"},
        "button_capitalization": "uppercase",
        "button_text": "#2186f4",
        "button_background_color": "#0e1012",
        "control_border": {
            "width": "0px 0px 1px 0px",
            "color": "#8F9FB5",
            "radius": "0px",
        },
        "control_background_color": "#0e1012",
        "control_text": "#A0AABA",
        "card_margin": "15px",
        "card_padding": "5px",
        "card_border": {
            "width": "0px 0px 0px 0px",
            "style": "solid",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "card_background_color": "#0e1012",
        "card_box_shadow": "0px 1px 3px rgba(0,0,0,0.12), 0px 1px 2px rgba(0,0,0,0.24)",
        "card_outline": {"width": "0px", "style": "solid", "color": "#e2e2e2"},
        "card_header_margin": "0px",
        "card_header_padding": "10px",
        "card_header_border": {
            "width": "0px 0px 1px 0px",
            "style": "solid",
            "color": "black",
            "radius": "0px",
        },
        "card_header_background_color": "#0e1012",
        "card_header_box_shadow": "0px 0px 0px rgba(0,0,0,0)",
        "breakpoint_font": "1200px",
        "breakpoint_stack_blocks": "700px",
        "colorway": [
            "#119dff",
            "#66c2a5",
            "#fc8d62",
            "#e78ac3",
            "#a6d854",
            "#ffd92f",
            "#e5c494",
            "#b3b3b3",
        ],
        "colorscale": [
            "#1f78b4",
            "#4786bc",
            "#6394c5",
            "#7ba3cd",
            "#92b1d5",
            "#a9c0de",
            "#bed0e6",
            "#d4dfee",
            "#eaeff7",
            "#ffffff",
        ],
        "dash_cloud_button_background_color": "#5166D1",
        "dbc_primary": "#3479f3",
        "dbc_secondary": "#69a6ff",
        "dbc_success": "#1baf73",
        "dbc_warning": "#ffad40",
        "dbc_danger": "#ff2c6d",
        "dbc_info": "#33cce5",
        "dbc_dark": "#282b2d",
        "dbc_light": "#ccd3d6",
        "dbc_gray": "#adb5bd",
        "font_family": "Open Sans, sans-serif",
        "font_family_header": "Open Sans, sans-serif",
        "font_family_headings": "Open Sans, sans-serif",
        "font_size": "14px",
        "font_size_smaller_screen": "13px",
        "font_size_header": "24px",
        "title_capitalization": "uppercase",
        "header_content_alignment": "spread",
        "header_margin": "0px 0px 15px 0px",
        "header_padding": "0px",
        "header_border": {
            "width": "0px 0px 0px 0px",
            "style": "solid",
            "color": "#e2e2e2",
            "radius": "0px",
        },
        "header_background_color": "black",
        "header_box_shadow": "0px 1px 3px rgba(0,0,0,0.12), 0px 1px 2px rgba(0,0,0,0.24)",
        "header_text": "#fff",
        "header_right_border_color": "1px solid var(--text)",
        "heading_text": "#fff",
        "kubernetes_banner_font_color": "#3f3f3f",
        "text": "#A0AABA",
        "report_background_content": "#FAFBFC",
        "report_background_page": "white",
        "report_text": "black",
        "report_font_family": "Computer Modern",
        "report_font_size": "12px",
    },
}
