# AUTO GENERATED FILE - DO NOT EDIT

agGridColumn <- function(children=NULL, id=NULL, aggFunc=NULL, allowedAggFuncs=NULL, autoHeight=NULL, cellClass=NULL, cellClassRules=NULL, cellEditor=NULL, cellEditorParams=NULL, cellRenderer=NULL, cellRendererParams=NULL, cellRendererSelector=NULL, cellStyle=NULL, chartDataType=NULL, checkboxSelection=NULL, colId=NULL, columnGroupShow=NULL, columnsMenuParams=NULL, defaultWidth=NULL, dndSource=NULL, dndSourceOnRowDrag=NULL, editable=NULL, enableCellChangeFlash=NULL, enablePivot=NULL, enableRowGroup=NULL, enableValue=NULL, field=NULL, filter=NULL, filterParams=NULL, flex=NULL, floatingFilter=NULL, floatingFilterComponent=NULL, floatingFilterComponentParams=NULL, getQuickFilterText=NULL, groupId=NULL, headerCheckboxSelection=NULL, headerCheckboxSelectionFilteredOnly=NULL, headerClass=NULL, headerComponent=NULL, headerComponentParams=NULL, headerGroupComponent=NULL, headerGroupComponentParams=NULL, headerName=NULL, headerTooltip=NULL, hide=NULL, initialAggFunc=NULL, initialFlex=NULL, initialHide=NULL, initialPinned=NULL, initialPivot=NULL, initialPivotIndex=NULL, initialRowGroup=NULL, initialRowGroupIndex=NULL, initialSort=NULL, initialSortIndex=NULL, lockPinned=NULL, lockPosition=NULL, lockVisible=NULL, marryChildren=NULL, maxWidth=NULL, menuTabs=NULL, minWidth=NULL, openByDefault=NULL, pinned=NULL, pinnedRowCellRenderer=NULL, pinnedRowCellRendererParams=NULL, pivot=NULL, pivotIndex=NULL, resizable=NULL, rowDrag=NULL, rowDragText=NULL, rowGroup=NULL, rowGroupIndex=NULL, singleClickEdit=NULL, sort=NULL, sortIndex=NULL, sortable=NULL, sortingOrder=NULL, style=NULL, suppressCellFlash=NULL, suppressColumnsToolPanel=NULL, suppressFiltersToolPanel=NULL, suppressMenu=NULL, suppressMovable=NULL, suppressNavigable=NULL, suppressSizeToFit=NULL, toolPanelClass=NULL, tooltipField=NULL, tooltipValueGetter=NULL, type=NULL, unSortIcon=NULL, width=NULL, wrapText=NULL) {
    
    props <- list(children=children, id=id, aggFunc=aggFunc, allowedAggFuncs=allowedAggFuncs, autoHeight=autoHeight, cellClass=cellClass, cellClassRules=cellClassRules, cellEditor=cellEditor, cellEditorParams=cellEditorParams, cellRenderer=cellRenderer, cellRendererParams=cellRendererParams, cellRendererSelector=cellRendererSelector, cellStyle=cellStyle, chartDataType=chartDataType, checkboxSelection=checkboxSelection, colId=colId, columnGroupShow=columnGroupShow, columnsMenuParams=columnsMenuParams, defaultWidth=defaultWidth, dndSource=dndSource, dndSourceOnRowDrag=dndSourceOnRowDrag, editable=editable, enableCellChangeFlash=enableCellChangeFlash, enablePivot=enablePivot, enableRowGroup=enableRowGroup, enableValue=enableValue, field=field, filter=filter, filterParams=filterParams, flex=flex, floatingFilter=floatingFilter, floatingFilterComponent=floatingFilterComponent, floatingFilterComponentParams=floatingFilterComponentParams, getQuickFilterText=getQuickFilterText, groupId=groupId, headerCheckboxSelection=headerCheckboxSelection, headerCheckboxSelectionFilteredOnly=headerCheckboxSelectionFilteredOnly, headerClass=headerClass, headerComponent=headerComponent, headerComponentParams=headerComponentParams, headerGroupComponent=headerGroupComponent, headerGroupComponentParams=headerGroupComponentParams, headerName=headerName, headerTooltip=headerTooltip, hide=hide, initialAggFunc=initialAggFunc, initialFlex=initialFlex, initialHide=initialHide, initialPinned=initialPinned, initialPivot=initialPivot, initialPivotIndex=initialPivotIndex, initialRowGroup=initialRowGroup, initialRowGroupIndex=initialRowGroupIndex, initialSort=initialSort, initialSortIndex=initialSortIndex, lockPinned=lockPinned, lockPosition=lockPosition, lockVisible=lockVisible, marryChildren=marryChildren, maxWidth=maxWidth, menuTabs=menuTabs, minWidth=minWidth, openByDefault=openByDefault, pinned=pinned, pinnedRowCellRenderer=pinnedRowCellRenderer, pinnedRowCellRendererParams=pinnedRowCellRendererParams, pivot=pivot, pivotIndex=pivotIndex, resizable=resizable, rowDrag=rowDrag, rowDragText=rowDragText, rowGroup=rowGroup, rowGroupIndex=rowGroupIndex, singleClickEdit=singleClickEdit, sort=sort, sortIndex=sortIndex, sortable=sortable, sortingOrder=sortingOrder, style=style, suppressCellFlash=suppressCellFlash, suppressColumnsToolPanel=suppressColumnsToolPanel, suppressFiltersToolPanel=suppressFiltersToolPanel, suppressMenu=suppressMenu, suppressMovable=suppressMovable, suppressNavigable=suppressNavigable, suppressSizeToFit=suppressSizeToFit, toolPanelClass=toolPanelClass, tooltipField=tooltipField, tooltipValueGetter=tooltipValueGetter, type=type, unSortIcon=unSortIcon, width=width, wrapText=wrapText)
    if (length(props) > 0) {
        props <- props[!vapply(props, is.null, logical(1))]
    }
    component <- list(
        props = props,
        type = 'AgGridColumn',
        namespace = 'dash_ag_grid',
        propNames = c('children', 'id', 'aggFunc', 'allowedAggFuncs', 'autoHeight', 'cellClass', 'cellClassRules', 'cellEditor', 'cellEditorParams', 'cellRenderer', 'cellRendererParams', 'cellRendererSelector', 'cellStyle', 'chartDataType', 'checkboxSelection', 'colId', 'columnGroupShow', 'columnsMenuParams', 'defaultWidth', 'dndSource', 'dndSourceOnRowDrag', 'editable', 'enableCellChangeFlash', 'enablePivot', 'enableRowGroup', 'enableValue', 'field', 'filter', 'filterParams', 'flex', 'floatingFilter', 'floatingFilterComponent', 'floatingFilterComponentParams', 'getQuickFilterText', 'groupId', 'headerCheckboxSelection', 'headerCheckboxSelectionFilteredOnly', 'headerClass', 'headerComponent', 'headerComponentParams', 'headerGroupComponent', 'headerGroupComponentParams', 'headerName', 'headerTooltip', 'hide', 'initialAggFunc', 'initialFlex', 'initialHide', 'initialPinned', 'initialPivot', 'initialPivotIndex', 'initialRowGroup', 'initialRowGroupIndex', 'initialSort', 'initialSortIndex', 'lockPinned', 'lockPosition', 'lockVisible', 'marryChildren', 'maxWidth', 'menuTabs', 'minWidth', 'openByDefault', 'pinned', 'pinnedRowCellRenderer', 'pinnedRowCellRendererParams', 'pivot', 'pivotIndex', 'resizable', 'rowDrag', 'rowDragText', 'rowGroup', 'rowGroupIndex', 'singleClickEdit', 'sort', 'sortIndex', 'sortable', 'sortingOrder', 'style', 'suppressCellFlash', 'suppressColumnsToolPanel', 'suppressFiltersToolPanel', 'suppressMenu', 'suppressMovable', 'suppressNavigable', 'suppressSizeToFit', 'toolPanelClass', 'tooltipField', 'tooltipValueGetter', 'type', 'unSortIcon', 'width', 'wrapText'),
        package = 'dashAgGrid'
        )

    structure(component, class = c('dash_component', 'list'))
}
