.dashAgGrid_js_metadata <- function() {
deps_metadata <- list(`dash_ag_grid` = structure(list(name = "dash_ag_grid",
version = "1.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_ag_grid.min.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAgGrid",
all_files = FALSE), class = "html_dependency"),
`dash_ag_grid` = structure(list(name = "dash_ag_grid",
version = "1.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'dash_ag_grid.min.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAgGrid",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"),
`dash_ag_grid` = structure(list(name = "dash_ag_grid",
version = "1.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-dashaggrid.js',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAgGrid",
all_files = FALSE, async = TRUE), class = "html_dependency"),
`dash_ag_grid` = structure(list(name = "dash_ag_grid",
version = "1.3.1", src = list(href = NULL,
file = "deps"), meta = NULL,
script = 'async-dashaggrid.js.map',
stylesheet = NULL, head = NULL, attachment = NULL, package = "dashAgGrid",
all_files = FALSE, dynamic = TRUE), class = "html_dependency"))
return(deps_metadata)
}
